[project]
name = "hangman"
version = "0.1.0"
description = "Python version of the known game 'Hangman'"
readme = "README.md"
requires-python = ">=3.11.6"
dependencies = [

]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
